import DevelopmentProgram from '../models/DevelopmentProgram.js';

const programs = [
  {
    federationCode: 'itf',
    federationName: 'ITF',
    fullName: 'International Tennis Federation',
    country: 'Miedzynarodowa',
    countryFlag: '🌍',
    description: 'Globalny standard rozwoju tenisisty — bazowe wytyczne ITF stosowane na calym swiecie.',
    genderNotes: 'Dziewczeta wchodza w etapy dojrzewania wczesniej (10-13 vs 12-15 u chlopcow). Obciazenia fizyczne dostosowane do fazy wzrostu.',
    source: 'ITF Player Development Guidelines, ITF Global Tennis Report',
    stages: [
      {
        code: 'pre_tennis',
        name: 'Pre-Tennis / FUNdamentals',
        namePl: 'Pre-Tenis / Fundamenty',
        ageRange: { boys: { min: 4, max: 6 }, girls: { min: 4, max: 6 } },
        recommendations: {
          totalHoursPerWeek: { min: 2, max: 4 },
          onCourtHours: { min: 1, max: 2 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['Zwinnosc', 'Rownowaga', 'Koordynacja', 'Szybkosc', 'Zabawa'],
        principles: 'Rozwoj ABCs (Agility, Balance, Coordination, Speed). Wielosportowość. Zabawa jest najwazniejsza.',
        trainingDistribution: { onCourt: 40, physical: 50, competition: 0, mentalRecovery: 10 },
      },
      {
        code: 'mini_tennis',
        name: 'Mini Tennis (Red/Orange/Green)',
        namePl: 'Mini Tenis (Czerwony/Pomarancz/Zielony)',
        ageRange: { boys: { min: 6, max: 9 }, girls: { min: 6, max: 9 } },
        recommendations: {
          totalHoursPerWeek: { min: 4, max: 6 },
          onCourtHours: { min: 3, max: 4 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 1 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Zmodyfikowany sprzet', 'Podstawy techniczne', 'Gra oparta na zabawie'],
        principles: 'Zmodyfikowane korty, pilki, rakiety (Tennis 10s). Fundamenty techniczne. 70-80% cwiczen oparte na grze.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 10, mentalRecovery: 10 },
      },
      {
        code: 'learn_to_train',
        name: 'Learn to Train',
        namePl: 'Naucz sie Trenowac',
        ageRange: { boys: { min: 9, max: 12 }, girls: { min: 8, max: 11 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 12 },
          onCourtHours: { min: 5, max: 8 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Zloty wiek motoryki', 'Szerokie podstawy techniczne', 'Wprowadzenie do rywalizacji'],
        principles: 'Zloty wiek uczenia motorycznego — szczytowa zdolnosc przyswajania umiejetnosci. Szerokie podstawy techniczne. Wprowadzenie do mentalnosci zawodniczej. Nadal wielosportowosc.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'train_to_train',
        name: 'Train to Train',
        namePl: 'Trenuj, by Trenowac',
        ageRange: { boys: { min: 12, max: 16 }, girls: { min: 11, max: 15 } },
        recommendations: {
          totalHoursPerWeek: { min: 12, max: 18 },
          onCourtHours: { min: 8, max: 12 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Adaptacje treningowe', 'Zarzadzanie dojrzewaniem', 'Doskonalenie techniki', 'Swiadomosc taktyczna'],
        principles: 'Glowne adaptacje treningowe. Zarzadzanie okresem dojrzewania. Specjalizacja zaczyna sie, ale nie wylaczna. Doskonalenie techniki i swiadomosc taktyczna.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'train_to_compete',
        name: 'Train to Compete',
        namePl: 'Trenuj, by Rywalizowac',
        ageRange: { boys: { min: 16, max: 18 }, girls: { min: 15, max: 17 } },
        recommendations: {
          totalHoursPerWeek: { min: 18, max: 25 },
          onCourtHours: { min: 10, max: 14 },
          physicalHours: { min: 5, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Tenis jako sport glowny', 'Periodyzacja', 'Kalendarz turniejowy', 'Trening mentalny'],
        principles: 'Tenis staje sie sportem glownym. Wysoki wolumen treningowy. Kalendarz turniejowy napedza periodyzacje.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'train_to_win',
        name: 'Train to Win',
        namePl: 'Trenuj, by Wygrywac',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 17, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 25, max: 30 },
          onCourtHours: { min: 12, max: 16 },
          physicalHours: { min: 6, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Pelne przygotowanie profesjonalne', 'Indywidualizacja', 'Sztab trenerski'],
        principles: 'Pelne przygotowanie profesjonalne. Programy w pelni zindywidualizowane.',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'usta',
    federationName: 'USTA',
    fullName: 'United States Tennis Association',
    country: 'USA',
    countryFlag: '🇺🇸',
    description: 'American Development Model — nacisk na wielosportowosc do 12 r.z., procesowe cele, sciezka college/pro.',
    genderNotes: 'USTA monitoruje obciazenie wzgledem dojrzewania (PHV). Dla dziewczat dodatkowy nacisk na profilaktyke ACL i zywienie w okresie dojrzewania.',
    source: 'USTA American Development Model, Player Development Competitive Pathway',
    stages: [
      {
        code: 'discover_learn',
        name: 'Discover & Learn',
        namePl: 'Odkrywaj i Ucz sie',
        ageRange: { boys: { min: 5, max: 8 }, girls: { min: 5, max: 8 } },
        recommendations: {
          totalHoursPerWeek: { min: 2, max: 5 },
          onCourtHours: { min: 2, max: 3 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['Zabawa', 'Red ball', 'Kort 36 stop', '3+ sporty'],
        principles: 'Brak rankingu i trofeow. Zabawa na pierwszym miejscu. 3+ sporty obowiazkowe. Red ball na korcie 36 stop.',
        trainingDistribution: { onCourt: 50, physical: 40, competition: 0, mentalRecovery: 10 },
      },
      {
        code: 'explore_build',
        name: 'Explore & Build',
        namePl: 'Eksploruj i Buduj',
        ageRange: { boys: { min: 8, max: 10 }, girls: { min: 8, max: 10 } },
        recommendations: {
          totalHoursPerWeek: { min: 5, max: 8 },
          onCourtHours: { min: 4, max: 6 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 1 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Orange ball', 'Kort 60 stop', 'Zrozumienie punktacji', 'Wysilek > wynik'],
        principles: 'Orange ball na korcie 60 stop. Poczatek zrozumienia punktacji. Wygrywanie mierzone wysilkiem, nie wynikami.',
        trainingDistribution: { onCourt: 65, physical: 20, competition: 10, mentalRecovery: 5 },
      },
      {
        code: 'learn_to_compete',
        name: 'Learn to Compete',
        namePl: 'Naucz sie Rywalizowac',
        ageRange: { boys: { min: 10, max: 12 }, girls: { min: 10, max: 12 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 14 },
          onCourtHours: { min: 6, max: 10 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Pelny kort', 'Rozwoj taktyczny', 'Cele procesowe', 'Turniejowy start'],
        principles: 'Przejscie na pelny kort. Rozwoj taktyczny. Cele procesowe, nie wynikowe.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'train_to_compete',
        name: 'Train to Compete',
        namePl: 'Trenuj, by Rywalizowac',
        ageRange: { boys: { min: 12, max: 15 }, girls: { min: 12, max: 15 } },
        recommendations: {
          totalHoursPerWeek: { min: 14, max: 20 },
          onCourtHours: { min: 9, max: 14 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Krytyczne okno rozwoju', 'Max 70% czasu w jednym sporcie do 14-15 lat'],
        principles: 'Krytyczne okno rozwoju. USTA zaleca max 70% czasu w jednym sporcie do 14-15 lat.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'compete_to_win',
        name: 'Compete to Win',
        namePl: 'Rywalizuj, by Wygrywac',
        ageRange: { boys: { min: 15, max: 18 }, girls: { min: 15, max: 18 } },
        recommendations: {
          totalHoursPerWeek: { min: 20, max: 28 },
          onCourtHours: { min: 12, max: 16 },
          physicalHours: { min: 5, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Specjalizacja', 'Sciezka high-performance', 'Periodyzacja', 'College pathway'],
        principles: 'Specjalizacja odpowiednia. Sciezka high-performance center (regionalne/krajowe centra). Rozwazona sciezka college.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'pro_transition',
        name: 'Win / Pro Transition',
        namePl: 'Wygrywaj / Tranzycja Pro',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 18, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 25, max: 35 },
          onCourtHours: { min: 14, max: 18 },
          physicalHours: { min: 6, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Przygotowanie profesjonalne', 'Bloki turniejowe', 'Periodyzacja zaawansowana'],
        principles: 'Pelne przygotowanie profesjonalne. Bloki turniejowe planowane rocznym kalendarzem.',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'tennis_canada',
    federationName: 'Tennis Canada',
    fullName: 'Tennis Canada',
    country: 'Kanada',
    countryFlag: '🇨🇦',
    description: 'Long-Term Player Development (LTPD) — najbardziej szczegolowy framework, oparty na modelu CS4L Istvana Balyi.',
    genderNotes: 'Dziewczeta wchodza w kazdy etap ok. 1 rok wczesniej. Etap Train to Train szczegolnie krytyczny dla dziewczat — baza tlenowa musi byc zbudowana w oknie 11-15 lat. Wyzsze ryzyko rezygnacji u dziewczat 12-14 lat.',
    source: 'Tennis Canada LTPD Framework, CS4L',
    stages: [
      {
        code: 'active_start',
        name: 'Active Start',
        namePl: 'Aktywny Start',
        ageRange: { boys: { min: 0, max: 6 }, girls: { min: 0, max: 6 } },
        recommendations: {
          totalHoursPerWeek: { min: 1, max: 2 },
          onCourtHours: { min: 1, max: 1 },
          physicalHours: { min: 0, max: 1 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 4,
        },
        multiSportRecommended: true,
        focusAreas: ['Zabawa ruchowa', 'Integracja przez gre'],
        principles: 'Zabawa ruchowa w zintegrowanej formie. Brak formalnego treningu.',
        trainingDistribution: { onCourt: 50, physical: 50, competition: 0, mentalRecovery: 0 },
      },
      {
        code: 'fundamentals',
        name: 'FUNdamentals',
        namePl: 'FUNdamenty',
        ageRange: { boys: { min: 6, max: 9 }, girls: { min: 6, max: 8 } },
        recommendations: {
          totalHoursPerWeek: { min: 3, max: 6 },
          onCourtHours: { min: 2, max: 4 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['Sprawnosc fizyczna', 'ABCs', 'Tenis 1 z 3-4 sportow', 'Zmodyfikowany sprzet'],
        principles: 'Sprawnosc fizyczna jest celem. Tenis jednym z 3-4 sportow. ABCs. Zmodyfikowany sprzet obowiazkowy.',
        trainingDistribution: { onCourt: 55, physical: 30, competition: 5, mentalRecovery: 10 },
      },
      {
        code: 'learn_to_train',
        name: 'Learn to Train',
        namePl: 'Naucz sie Trenowac',
        ageRange: { boys: { min: 9, max: 12 }, girls: { min: 8, max: 11 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 12 },
          onCourtHours: { min: 5, max: 8 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Zloty wiek motoryczny', 'Priorytet techniczny', 'Budowa uderzen', 'Sampling sportow'],
        principles: 'Zloty wiek uczenia motorycznego. Umiejetnosci techniczne sa priorytetem. Budowa wszystkich uderzen. Sampling wielosportowy.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'train_to_train',
        name: 'Train to Train',
        namePl: 'Trenuj, by Trenowac',
        ageRange: { boys: { min: 12, max: 16 }, girls: { min: 11, max: 15 } },
        recommendations: {
          totalHoursPerWeek: { min: 12, max: 20 },
          onCourtHours: { min: 8, max: 14 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Etap make or break', 'Baza tlenowa', 'Monitoring dojrzewania', 'Periodyzacja'],
        principles: 'Etap "make or break". Budowanie bazy tlenowej. Monitoring wzrostu i dojrzewania krytyczny. Wprowadzenie periodyzacji.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'train_to_compete',
        name: 'Train to Compete',
        namePl: 'Trenuj, by Rywalizowac',
        ageRange: { boys: { min: 16, max: 18 }, girls: { min: 15, max: 17 } },
        recommendations: {
          totalHoursPerWeek: { min: 20, max: 28 },
          onCourtHours: { min: 12, max: 16 },
          physicalHours: { min: 5, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Tenis caloroczny', 'Pelna periodyzacja', 'Trening mentalny', 'Kalendarz turniejowy'],
        principles: 'Tenis caloroczny. Pelna periodyzacja. Trening umiejetnosci mentalnych sformalizowany. Planowanie kalendarza turniejowego.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'train_to_win',
        name: 'Train to Win',
        namePl: 'Trenuj, by Wygrywac',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 17, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 25, max: 35 },
          onCourtHours: { min: 14, max: 18 },
          physicalHours: { min: 6, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Pelen indywidualizm', 'Rywalizacja miedzynarodowa', 'Sztab szkoleniowy'],
        principles: 'Pelna indywidualizacja. Rywalizacja miedzynarodowa. Zespol wspierajacy (trener, fizjo, mentalista, dietetyk).',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'tennis_australia',
    federationName: 'Tennis Australia',
    fullName: 'Tennis Australia',
    country: 'Australia',
    countryFlag: '🇦🇺',
    description: 'Hot Shots → Elite pathway — silny program mlodziezowy z wczesnym wlaczeniem do gier meczowych.',
    genderNotes: 'Podobne rekomendacje godzinowe dla obu plci. Specjalny nacisk na badanie RED-S u zawodniczek.',
    source: 'Tennis Australia Hot Shots Program, National Development Squad Pathway',
    stages: [
      {
        code: 'hot_shots_blue_red',
        name: 'Hot Shots (Blue/Red)',
        namePl: 'Hot Shots (Niebieski/Czerwony)',
        ageRange: { boys: { min: 3, max: 7 }, girls: { min: 3, max: 7 } },
        recommendations: {
          totalHoursPerWeek: { min: 1, max: 3 },
          onCourtHours: { min: 1, max: 2 },
          physicalHours: { min: 0, max: 1 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['3+ sporty', 'Uczenie przez gre', 'Play and Stay'],
        principles: 'Progresywny system pilek/kortow. Nauka przez gre. Filozofia Play and Stay.',
        trainingDistribution: { onCourt: 55, physical: 35, competition: 0, mentalRecovery: 10 },
      },
      {
        code: 'hot_shots_orange_green',
        name: 'Hot Shots (Orange/Green)',
        namePl: 'Hot Shots (Pomaranczowy/Zielony)',
        ageRange: { boys: { min: 7, max: 10 }, girls: { min: 7, max: 10 } },
        recommendations: {
          totalHoursPerWeek: { min: 4, max: 8 },
          onCourtHours: { min: 3, max: 6 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 1 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Gry zmodyfikowane', 'Podstawy meczowe', '2-3 sporty'],
        principles: 'Progresywna modyfikacja sprzetu. Gra zmodyfikowana. 2-3 sporty uzupelniajace.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 10, mentalRecovery: 10 },
      },
      {
        code: 'foundation',
        name: 'Foundation',
        namePl: 'Fundament',
        ageRange: { boys: { min: 10, max: 13 }, girls: { min: 10, max: 13 } },
        recommendations: {
          totalHoursPerWeek: { min: 10, max: 15 },
          onCourtHours: { min: 7, max: 10 },
          physicalHours: { min: 3, max: 5 },
          competitionHours: { min: 1, max: 3 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Doskonalosc techniczna', 'Warunki meczowe', 'Struktura zawodow'],
        principles: 'Doskonalosc techniczna w warunkach meczowych. Wprowadzenie do struktury zawodow.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'talent',
        name: 'Talent',
        namePl: 'Talent',
        ageRange: { boys: { min: 13, max: 16 }, girls: { min: 13, max: 16 } },
        recommendations: {
          totalHoursPerWeek: { min: 15, max: 22 },
          onCourtHours: { min: 10, max: 14 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Akademie stanowe/krajowe', 'Periodyzacja', 'Ekspozycja miedzynarodowa'],
        principles: 'Zidentyfikowani zawodnicy wchodza do akademii. Periodyzacja. Poczatek ekspozycji miedzynarodowej.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'elite',
        name: 'Elite',
        namePl: 'Elita',
        ageRange: { boys: { min: 16, max: 18 }, girls: { min: 16, max: 18 } },
        recommendations: {
          totalHoursPerWeek: { min: 22, max: 30 },
          onCourtHours: { min: 14, max: 18 },
          physicalHours: { min: 6, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Akademia Narodowa', 'Pelny etat', 'Edukacja zintegrowana'],
        principles: 'Akademia Narodowa. Srodowisko treningowe na pelny etat. Edukacja zintegrowana.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'professional',
        name: 'Professional',
        namePl: 'Profesjonalista',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 18, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 28, max: 35 },
          onCourtHours: { min: 15, max: 20 },
          physicalHours: { min: 8, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Wsparcie tranzycyjne', 'Planowanie tury', 'Wildcards'],
        principles: 'Program wsparcia tranzycyjnego. Planowanie tury. Wildcards do Australian Open.',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'fft',
    federationName: 'FFT',
    fullName: 'Federation Francaise de Tennis',
    country: 'Francja',
    countryFlag: '🇫🇷',
    description: 'System formation — oparty na klubach, wczesna klasyfikacja, sciezka Pole France do centrum Roland Garros.',
    genderNotes: 'Ta sama sciezka strukturalna dla chlopcow i dziewczat. Program retencji dziewczat "Toutes en Jeu".',
    source: 'FFT Formation Structure, Pole France Pathway',
    stages: [
      {
        code: 'mini_tennis',
        name: 'Mini Tennis',
        namePl: 'Mini Tenis',
        ageRange: { boys: { min: 4, max: 6 }, girls: { min: 4, max: 6 } },
        recommendations: {
          totalHoursPerWeek: { min: 2, max: 3 },
          onCourtHours: { min: 1, max: 2 },
          physicalHours: { min: 1, max: 1 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['Klub', 'Zabawa', 'Plateau events'],
        principles: 'Baza klubowa. Zabawa. Imprezy "plateau" bez rankingu.',
        trainingDistribution: { onCourt: 50, physical: 40, competition: 0, mentalRecovery: 10 },
      },
      {
        code: 'club_formation',
        name: 'Club Formation',
        namePl: 'Formacja Klubowa',
        ageRange: { boys: { min: 6, max: 10 }, girls: { min: 6, max: 10 } },
        recommendations: {
          totalHoursPerWeek: { min: 4, max: 8 },
          onCourtHours: { min: 3, max: 6 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 1 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Trening klubowy', 'Poczatek classement (~8 lat)', 'Zawody departamentalne'],
        principles: 'Trening w klubie. Poczatek systemu klasyfikacji (classement) od ok. 8 lat.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 10, mentalRecovery: 10 },
      },
      {
        code: 'departmental',
        name: 'Departmental Training',
        namePl: 'Trening Departamentalny',
        ageRange: { boys: { min: 10, max: 12 }, girls: { min: 10, max: 12 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 14 },
          onCourtHours: { min: 6, max: 10 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Selekcja do centrow', 'Zawody regionalne', 'Rozwoj techniczny'],
        principles: 'Selekcja do centrow treningowych. Zawody departamentalne/regionalne.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'pole_regional',
        name: 'Pole France / Regional',
        namePl: 'Pole France / Regionalny',
        ageRange: { boys: { min: 12, max: 15 }, girls: { min: 12, max: 15 } },
        recommendations: {
          totalHoursPerWeek: { min: 15, max: 22 },
          onCourtHours: { min: 10, max: 14 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Sport-etudes', 'Szkolenie rano / trening po poludniu', 'Zawody krajowe/europejskie'],
        principles: 'Program sport-etudes: szkola rano, trening po poludniu. Zawody krajowe i europejskie.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'pole_national',
        name: 'Pole France National',
        namePl: 'Pole France Krajowy',
        ageRange: { boys: { min: 15, max: 18 }, girls: { min: 15, max: 18 } },
        recommendations: {
          totalHoursPerWeek: { min: 22, max: 30 },
          onCourtHours: { min: 14, max: 18 },
          physicalHours: { min: 6, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['CNE Roland Garros', '~30 chlopcow + 30 dziewczat', 'Rywalizacja miedzynarodowa'],
        principles: 'Centre National d\'Entrainement przy Roland Garros. Ok. 30 chlopcow i 30 dziewczat.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'pro_pathway',
        name: 'Pro Pathway',
        namePl: 'Sciezka Profesjonalna',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 18, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 30, max: 35 },
          onCourtHours: { min: 16, max: 20 },
          physicalHours: { min: 8, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Sztab FFT', 'Pelen profesjonalizm', 'Technika w sluzbie gry'],
        principles: 'Pelny profesjonalizm. Filozofia "la technique au service du jeu" — technika w sluzbie gry.',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'lta',
    federationName: 'LTA',
    fullName: 'Lawn Tennis Association',
    country: 'Wielka Brytania',
    countryFlag: '🇬🇧',
    description: 'Tennis Opened Up — nacisk na dostepnosc i uczestnictwo przed wynikami, centra RPDC w calym UK.',
    genderNotes: 'Program "She Rallies" dla retencji dziewczat. Nacisk na wspierajace srodowisko w etapie Commit & Develop.',
    source: 'LTA Player Pathway, Tennis Opened Up Framework',
    stages: [
      {
        code: 'start_enjoy',
        name: 'Start & Enjoy',
        namePl: 'Zacznij i Ciesz sie',
        ageRange: { boys: { min: 4, max: 7 }, girls: { min: 4, max: 7 } },
        recommendations: {
          totalHoursPerWeek: { min: 1, max: 3 },
          onCourtHours: { min: 1, max: 2 },
          physicalHours: { min: 0, max: 1 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['Red ball', 'Zabawa', 'Brak formalnych wynikow'],
        principles: 'Zabawa na korcie. Red ball. Brak formalnych zawodow i wynikow.',
        trainingDistribution: { onCourt: 55, physical: 35, competition: 0, mentalRecovery: 10 },
      },
      {
        code: 'explore_build',
        name: 'Explore & Build',
        namePl: 'Eksploruj i Buduj',
        ageRange: { boys: { min: 7, max: 9 }, girls: { min: 7, max: 9 } },
        recommendations: {
          totalHoursPerWeek: { min: 3, max: 6 },
          onCourtHours: { min: 2, max: 4 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 1 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Orange ball', 'Fun Competitions', 'Eksploracja'],
        principles: 'Orange ball. Zabawa w zawodach. Eksploracja roznych aspektow gry.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 10, mentalRecovery: 10 },
      },
      {
        code: 'commit_develop',
        name: 'Commit & Develop',
        namePl: 'Zaangazuj sie i Rozwijaj',
        ageRange: { boys: { min: 9, max: 12 }, girls: { min: 9, max: 12 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 14 },
          onCourtHours: { min: 6, max: 10 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Green/Yellow ball', 'Zawody County/Regional', 'Rozwoj techniki'],
        principles: 'Przejscie na green/yellow ball. Zawody County i Regional (~20% czasu).',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'challenge_compete',
        name: 'Challenge & Compete',
        namePl: 'Wyzwanie i Rywalizacja',
        ageRange: { boys: { min: 12, max: 15 }, girls: { min: 12, max: 15 } },
        recommendations: {
          totalHoursPerWeek: { min: 14, max: 22 },
          onCourtHours: { min: 10, max: 14 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Zawody krajowe', 'RPDC', 'Rozwoj fizyczny'],
        principles: 'Zawody krajowe (~25% czasu). Regional Player Development Centres.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'excel_win',
        name: 'Excel & Win',
        namePl: 'Osiagnij i Wygrywaj',
        ageRange: { boys: { min: 15, max: 18 }, girls: { min: 15, max: 18 } },
        recommendations: {
          totalHoursPerWeek: { min: 22, max: 30 },
          onCourtHours: { min: 14, max: 18 },
          physicalHours: { min: 6, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Rywalizacja miedzynarodowa', 'NTC Roehampton', 'Partnerstwa uczelni'],
        principles: 'Rywalizacja miedzynarodowa (~30% czasu). National Tennis Centre. Partnerstwa z uczelniami.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'elite_performance',
        name: 'Elite Performance',
        namePl: 'Elitarny Wynik',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 18, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 28, max: 35 },
          onCourtHours: { min: 16, max: 20 },
          physicalHours: { min: 8, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Tour', 'Pelny profesjonalizm'],
        principles: 'Pelny profesjonalizm. Indywidualny sztab szkoleniowy.',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'dtb',
    federationName: 'DTB',
    fullName: 'Deutscher Tennis Bund',
    country: 'Niemcy',
    countryFlag: '🇩🇪',
    description: 'Silny system ligowy (Mannschaft), Bundesleistungszentren, Talentinos — nacisk na przygotowanie atletyczne.',
    genderNotes: 'Podobne rekomendacje godzinowe. Potencjalnie wyzszy wspolczynnik treningu fizycznego niz inne federacje.',
    source: 'DTB Talentinos Program, Bundesleistungszentren Guidelines',
    stages: [
      {
        code: 'grundlagentraining',
        name: 'Grundlagentraining',
        namePl: 'Trening Podstaw',
        ageRange: { boys: { min: 6, max: 9 }, girls: { min: 6, max: 9 } },
        recommendations: {
          totalHoursPerWeek: { min: 3, max: 6 },
          onCourtHours: { min: 2, max: 4 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 1 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Talentinos', 'Klub', 'Liga druzyanowa (Mannschaft)'],
        principles: 'Program Talentinos. Trening klubowy. Wczesna liga druzynowa buduje odpornosc psychiczna.',
        trainingDistribution: { onCourt: 55, physical: 30, competition: 5, mentalRecovery: 10 },
      },
      {
        code: 'aufbautraining',
        name: 'Aufbautraining',
        namePl: 'Trening Rozwojowy',
        ageRange: { boys: { min: 9, max: 12 }, girls: { min: 9, max: 12 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 14 },
          onCourtHours: { min: 6, max: 10 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Zawody regionalne/Verband', 'Rozwoj techniczny', 'Atletyzm'],
        principles: 'Zawody regionalne. Rozwoj techniczny z silnym naciskiem na atletyzm.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'anschlusstraining',
        name: 'Anschlusstraining',
        namePl: 'Trening Lacznikowy',
        ageRange: { boys: { min: 12, max: 15 }, girls: { min: 12, max: 15 } },
        recommendations: {
          totalHoursPerWeek: { min: 14, max: 22 },
          onCourtHours: { min: 10, max: 14 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Bundesstützpunkte', 'Zawody krajowe/europejskie', 'Dual career'],
        principles: 'Regionalne bazy treningowe (Bundesstützpunkte). Zawody krajowe i europejskie. Dual career (edukacja + tenis).',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'leistungstraining',
        name: 'Leistungstraining',
        namePl: 'Trening Wyczynowy',
        ageRange: { boys: { min: 15, max: 18 }, girls: { min: 15, max: 18 } },
        recommendations: {
          totalHoursPerWeek: { min: 22, max: 30 },
          onCourtHours: { min: 14, max: 18 },
          physicalHours: { min: 6, max: 8 },
          competitionHours: { min: 3, max: 5 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Rywalizacja miedzynarodowa', 'Periodyzacja', 'Profesjonalizacja'],
        principles: 'Rywalizacja miedzynarodowa. Pelna periodyzacja. Profesjonalizacja podejscia.',
        trainingDistribution: { onCourt: 50, physical: 25, competition: 18, mentalRecovery: 7 },
      },
      {
        code: 'hochleistungstraining',
        name: 'Hochleistungstraining',
        namePl: 'Trening Najwyzszego Poziomu',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 18, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 28, max: 35 },
          onCourtHours: { min: 16, max: 20 },
          physicalHours: { min: 8, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Tour profesjonalny', 'Pelna indywidualizacja'],
        principles: 'Tour profesjonalny. Pelna indywidualizacja programu.',
        trainingDistribution: { onCourt: 45, physical: 25, competition: 20, mentalRecovery: 10 },
      },
    ],
  },
  {
    federationCode: 'rfet',
    federationName: 'RFET',
    fullName: 'Real Federacion Espanola de Tenis',
    country: 'Hiszpania',
    countryFlag: '🇪🇸',
    description: 'System akademiczny — wysoki wolumen na korcie (mączka), wczesna ekspozycja turniejowa, kultura grup treningowych.',
    genderNotes: 'Historycznie silniejsze programy meskie. Ostatnio zwiekszone inwestycje w rozwoj kobiet. Wolumeny treningowe podobne, choć zawodniczki trenowaly czasem przy nieco nizszych wolumenach.',
    source: 'RFET Academy Development Structure, National Pathway',
    stages: [
      {
        code: 'iniciacion',
        name: 'Iniciacion',
        namePl: 'Inicjacja',
        ageRange: { boys: { min: 5, max: 8 }, girls: { min: 5, max: 8 } },
        recommendations: {
          totalHoursPerWeek: { min: 3, max: 5 },
          onCourtHours: { min: 2, max: 3 },
          physicalHours: { min: 1, max: 2 },
          competitionHours: { min: 0, max: 0 },
          restDaysPerWeek: 3,
        },
        multiSportRecommended: true,
        focusAreas: ['Imprezy wewnetrzne', 'Zabawa', 'Grupa treningowa'],
        principles: 'Imprezy wewnetrzne akademii. Zabawa. Trening w grupie (4-6 graczy na korcie).',
        trainingDistribution: { onCourt: 50, physical: 40, competition: 0, mentalRecovery: 10 },
      },
      {
        code: 'formacion',
        name: 'Formacion',
        namePl: 'Formacja',
        ageRange: { boys: { min: 8, max: 12 }, girls: { min: 8, max: 12 } },
        recommendations: {
          totalHoursPerWeek: { min: 8, max: 14 },
          onCourtHours: { min: 6, max: 10 },
          physicalHours: { min: 2, max: 4 },
          competitionHours: { min: 1, max: 2 },
          restDaysPerWeek: 2,
        },
        multiSportRecommended: true,
        focusAreas: ['Wysoki wolumen kortowy', 'Zawody regionalne/krajowe', 'Filozofia mączki'],
        principles: 'Wysoki wolumen na korcie, szczegolnie na maczce. Dluzsze wymiany = wiecej powtorzen. Wczesna ekspozycja turniejowa od 10-12 lat.',
        trainingDistribution: { onCourt: 60, physical: 20, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'perfeccionamiento',
        name: 'Perfeccionamiento',
        namePl: 'Doskonalenie',
        ageRange: { boys: { min: 12, max: 16 }, girls: { min: 12, max: 16 } },
        recommendations: {
          totalHoursPerWeek: { min: 16, max: 24 },
          onCourtHours: { min: 10, max: 16 },
          physicalHours: { min: 4, max: 6 },
          competitionHours: { min: 2, max: 4 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Zawody krajowe/miedzynarodowe', 'Budowa punktu', 'Wzorce taktyczne', 'Inteligencja meczowa'],
        principles: 'Zawody krajowe i miedzynarodowe. Nacisk na budowe punktu, wzorce taktyczne i inteligencje meczowa.',
        trainingDistribution: { onCourt: 55, physical: 25, competition: 15, mentalRecovery: 5 },
      },
      {
        code: 'alto_rendimiento',
        name: 'Alto Rendimiento',
        namePl: 'Wysoka Wydajnosc',
        ageRange: { boys: { min: 16, max: 18 }, girls: { min: 16, max: 18 } },
        recommendations: {
          totalHoursPerWeek: { min: 24, max: 32 },
          onCourtHours: { min: 14, max: 20 },
          physicalHours: { min: 6, max: 8 },
          competitionHours: { min: 4, max: 6 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Rywalizacja miedzynarodowa', 'Trening calodniowy', 'Presja turniejowa'],
        principles: 'Rywalizacja miedzynarodowa. Trening calodniowy. Najwyzsze akademie (Sanchez-Casal, Nadal Academy, Equelite).',
        trainingDistribution: { onCourt: 50, physical: 22, competition: 20, mentalRecovery: 8 },
      },
      {
        code: 'profesional',
        name: 'Profesional',
        namePl: 'Profesjonalista',
        ageRange: { boys: { min: 18, max: 25 }, girls: { min: 18, max: 25 } },
        recommendations: {
          totalHoursPerWeek: { min: 30, max: 35 },
          onCourtHours: { min: 16, max: 22 },
          physicalHours: { min: 8, max: 10 },
          competitionHours: { min: 5, max: 8 },
          restDaysPerWeek: 1,
        },
        multiSportRecommended: false,
        focusAreas: ['Tour profesjonalny', 'Trening grupowy (4-6 graczy)', 'Klimat calodniowy'],
        principles: 'Tour profesjonalny. Trening grupowy w akademiach (presja rywalizacyjna). Calodniowy klimat umozliwia trening na dworze caly rok.',
        trainingDistribution: { onCourt: 50, physical: 22, competition: 20, mentalRecovery: 8 },
      },
    ],
  },
];

export async function seedDevelopmentPrograms() {
  console.log('Tworzenie programow rozwoju federacji...');
  await DevelopmentProgram.deleteMany({});

  for (const program of programs) {
    await DevelopmentProgram.create(program);
  }

  console.log(`  Utworzono ${programs.length} programow federacji`);
  return await DevelopmentProgram.find({});
}
